spring:
  jpa:
    properties:
      hibernate:
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    baseline-on-migrate: false
    enabled: true
  datasource:
    url: jdbc:h2:file:/Users/David/GimbTest
    username: sa
    password:
    driver-class-name: org.h2.Driver
